// SPDX-License-Identifier: GPL-3.0-or-later
// Mak Menu & Shell UI Style Controller
// Manages consistent macOS dual-layer borders, continuous corner radii, and specular highlights across GNOME Shell.

import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import St from 'gi://St';
import * as Main from 'resource:///org/gnome/shell/ui/main.js';

export class MenuStyleController {
    constructor(extension) {
        this._extension = extension;
        this._settings = extension.getSettings('org.gnome.shell.extensions.mak');
        this._settingsChangedId = 0;
        this._styleFile = null;
        this._isLoaded = false;
    }

    enable() {
        const extPath = this._extension.path;
        this._stylePath = GLib.build_filenamev([extPath, 'dynamic-menus.css']);
        this._styleFile = Gio.File.new_for_path(this._stylePath);

        this._settingsChangedId = this._settings.connect('changed', (s, key) => {
            if (key.startsWith('menu-') || key.startsWith('quick-settings-') || key.startsWith('notification-')) {
                this.updateStyles();
            }
        });

        this.updateStyles();
        console.log('[Mak Appearance] Menu & Shell UI styling controller active.');
    }

    disable() {
        if (this._settingsChangedId) {
            this._settings.disconnect(this._settingsChangedId);
            this._settingsChangedId = 0;
        }

        this._unloadCustomStylesheet();

        try {
            if (this._styleFile && this._styleFile.query_exists(null)) {
                this._styleFile.delete(null);
            }
        } catch (e) {}

        this._styleFile = null;
        this._isLoaded = false;
    }

    updateStyles() {
        const radius = this._settings.get_int('menu-corner-radius');
        const borderWidth = this._settings.get_int('menu-border-width');
        const borderOpacity = this._settings.get_double('menu-border-opacity');
        const specular = this._settings.get_boolean('menu-specular-highlight');
        const bgOpacity = this._settings.get_double('menu-bg-opacity');
        const qsRadius = this._settings.get_int('quick-settings-radius');
        const notifRadius = this._settings.get_int('notification-radius');

        const borderCss = borderWidth > 0
            ? `${borderWidth}px solid rgba(255, 255, 255, ${borderOpacity.toFixed(2)})`
            : 'none';

        const specularCss = specular
            ? 'inset 0 1px 0 rgba(255, 255, 255, 0.22), inset 0 0 0 1px rgba(255, 255, 255, 0.08),'
            : '';

        const css = `/* Generated by Mak Appearance Controller */
/* ── Unified macOS Popup Menus, Context Menus & Kiwi Menu ─────────────────── */
.popup-menu-content,
.popup-sub-menu,
.candidate-popup-content {
    border-radius: ${radius}px !important;
    border: ${borderCss} !important;
    background-color: rgba(36, 36, 42, ${bgOpacity.toFixed(2)}) !important;
    box-shadow: ${specularCss} 0 16px 38px rgba(0, 0, 0, 0.42) !important;
    padding: 6px !important;
}

/* ── Menu Items & Hover States ────────────────────────────────────────────── */
.popup-menu-item {
    border-radius: ${Math.max(4, radius - 8)}px !important;
    margin: 2px 4px !important;
    padding: 6px 12px !important;
    transition-duration: 100ms !important;
    color: #f0f0f0 !important;
}

.popup-menu-item:hover,
.popup-menu-item:focus {
    background-color: rgba(255, 255, 255, 0.14) !important;
    color: #ffffff !important;
}

.popup-menu-item:active {
    background-color: rgba(255, 255, 255, 0.24) !important;
    color: #ffffff !important;
}

.popup-menu-item.selected {
    background-color: rgba(255, 255, 255, 0.18) !important;
    color: #ffffff !important;
}

/* ── Separator ────────────────────────────────────────────────────────────── */
.popup-separator-menu-item {
    margin: 5px 8px !important;
    padding: 0 !important;
}

.popup-separator-menu-item .popup-separator-menu-item-separator {
    height: 1px !important;
    background-color: rgba(255, 255, 255, 0.10) !important;
}

/* ── Quick Settings Control Center ────────────────────────────────────────── */
.quick-settings,
.quick-toggle-menu {
    border-radius: ${qsRadius}px !important;
    border: ${borderCss} !important;
    box-shadow: ${specularCss} 0 20px 48px rgba(0, 0, 0, 0.48) !important;
}

/* ── Notification Banners ─────────────────────────────────────────────────── */
.notification-banner {
    border-radius: ${notifRadius}px !important;
    border: ${borderCss} !important;
    box-shadow: ${specularCss} 0 14px 34px rgba(0, 0, 0, 0.38) !important;
}

/* ── Modal Dialogs ────────────────────────────────────────────────────────── */
.modal-dialog {
    border-radius: ${Math.max(16, radius + 4)}px !important;
    border: ${borderCss} !important;
    box-shadow: ${specularCss} 0 24px 56px rgba(0, 0, 0, 0.52) !important;
}
`;

        try {
            GLib.file_set_contents(this._stylePath, css);
            this._reloadCustomStylesheet();
        } catch (err) {
            console.warn('[Mak Appearance] Error writing dynamic stylesheet:', err);
        }
    }

    _reloadCustomStylesheet() {
        this._unloadCustomStylesheet();

        try {
            const themeContext = St.ThemeContext.get_for_stage(global.stage);
            const theme = themeContext?.get_theme();
            if (theme && this._styleFile) {
                theme.load_stylesheet(this._styleFile);
                this._isLoaded = true;
            }
        } catch (err) {
            console.warn('[Mak Appearance] Error loading custom stylesheet:', err);
        }
    }

    _unloadCustomStylesheet() {
        if (this._isLoaded && this._styleFile) {
            try {
                const themeContext = St.ThemeContext.get_for_stage(global.stage);
                const theme = themeContext?.get_theme();
                if (theme) {
                    theme.unload_stylesheet(this._styleFile);
                }
            } catch (err) {
                console.warn('[Mak Appearance] Error unloading stylesheet:', err);
            }
            this._isLoaded = false;
        }
    }
}
